--- #YAML:1.0
name:                Net-RawIP
version:             0.24
abstract:            Perl extension for manipulate raw ip packets with interface to B<libpcap>
license:             perl
author:              
    - Sebastien Aperghis-Tramoni <sebastien@aperghis.net>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Class::Struct:                 0
    Data::Dumper:                  0
    English:                       0
    Getopt::Long:                  0
    Socket:                        0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
